/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Role = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
export const AiMessageState = IDL.Record({
  'content' : IDL.Text,
  'role' : Role,
  'timestamp' : IDL.Int,
});
export const Status__1 = IDL.Variant({
  'arrived' : IDL.Null,
  'loaded' : IDL.Null,
  'inTransit' : IDL.Null,
  'collected' : IDL.Null,
  'checkedIn' : IDL.Null,
  'atCarousel' : IDL.Null,
});
export const BaggageItemState = IDL.Record({
  'status' : Status__1,
  'lastUpdated' : IDL.Int,
  'description' : IDL.Text,
  'tagNumber' : IDL.Text,
});
export const DocType = IDL.Variant({
  'passport' : IDL.Null,
  'visa' : IDL.Null,
  'hotelBooking' : IDL.Null,
  'boardingPass' : IDL.Null,
  'travelInsurance' : IDL.Null,
});
export const DigitalIdentityDocState = IDL.Record({
  'expiryDate' : IDL.Int,
  'isReady' : IDL.Bool,
  'notes' : IDL.Text,
  'docType' : DocType,
});
export const Checkpoint = IDL.Variant({
  'checkin' : IDL.Null,
  'security' : IDL.Null,
  'boarding' : IDL.Null,
});
export const CongestionLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const QueueStatusState = IDL.Record({
  'checkpoint' : Checkpoint,
  'lastUpdated' : IDL.Int,
  'waitMinutes' : IDL.Nat,
  'congestionLevel' : CongestionLevel,
});
export const DisruptionType = IDL.Variant({
  'overbooking' : IDL.Null,
  'delay' : IDL.Null,
  'cancellation' : IDL.Null,
  'missedConnection' : IDL.Null,
});
export const TravelRightsInfoState = IDL.Record({
  'actionSteps' : IDL.Vec(IDL.Text),
  'compensationAmount' : IDL.Nat,
  'disruptionType' : DisruptionType,
  'applicableRegulation' : IDL.Text,
  'keyRights' : IDL.Vec(IDL.Text),
});
export const TripState = IDL.Record({
  'bookingReference' : IDL.Text,
  'arrivalAirport' : IDL.Text,
  'flightNumber' : IDL.Text,
  'seat' : IDL.Text,
  'departureTimestamp' : IDL.Int,
  'passengerName' : IDL.Text,
  'airline' : IDL.Text,
  'departureAirport' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Status = IDL.Variant({
  'delayed' : IDL.Null,
  'cancelled' : IDL.Null,
  'gateChange' : IDL.Null,
  'onTime' : IDL.Null,
});
export const FlightStatusState = IDL.Record({
  'status' : Status,
  'flightNumber' : IDL.Text,
  'gate' : IDL.Text,
  'message' : IDL.Text,
  'delayMinutes' : IDL.Opt(IDL.Nat),
  'terminal' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAiMessage' : IDL.Func([AiMessageState], [], []),
  'addOrUpdateBaggageItem' : IDL.Func([BaggageItemState], [], []),
  'addOrUpdateDigitalIdentityDoc' : IDL.Func([DigitalIdentityDocState], [], []),
  'addOrUpdateQueueStatus' : IDL.Func([QueueStatusState], [], []),
  'addTravelRightsInfo' : IDL.Func([TravelRightsInfoState], [], []),
  'addTrip' : IDL.Func([TripState], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'computeLeaveHomeTime' : IDL.Func([], [IDL.Int], ['query']),
  'getAiMessages' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AiMessageState)],
      ['query'],
    ),
  'getBaggageItems' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(BaggageItemState)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDigitalIdentityDocs' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DigitalIdentityDocState)],
      ['query'],
    ),
  'getFlightStatus' : IDL.Func([IDL.Text], [FlightStatusState], ['query']),
  'getQueueStatuses' : IDL.Func([], [IDL.Vec(QueueStatusState)], ['query']),
  'getTravelRightsInfo' : IDL.Func(
      [IDL.Text],
      [TravelRightsInfoState],
      ['query'],
    ),
  'getTrip' : IDL.Func([IDL.Principal], [TripState], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedDemoData' : IDL.Func([], [], []),
  'updateFlightStatus' : IDL.Func([FlightStatusState], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Role = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
  const AiMessageState = IDL.Record({
    'content' : IDL.Text,
    'role' : Role,
    'timestamp' : IDL.Int,
  });
  const Status__1 = IDL.Variant({
    'arrived' : IDL.Null,
    'loaded' : IDL.Null,
    'inTransit' : IDL.Null,
    'collected' : IDL.Null,
    'checkedIn' : IDL.Null,
    'atCarousel' : IDL.Null,
  });
  const BaggageItemState = IDL.Record({
    'status' : Status__1,
    'lastUpdated' : IDL.Int,
    'description' : IDL.Text,
    'tagNumber' : IDL.Text,
  });
  const DocType = IDL.Variant({
    'passport' : IDL.Null,
    'visa' : IDL.Null,
    'hotelBooking' : IDL.Null,
    'boardingPass' : IDL.Null,
    'travelInsurance' : IDL.Null,
  });
  const DigitalIdentityDocState = IDL.Record({
    'expiryDate' : IDL.Int,
    'isReady' : IDL.Bool,
    'notes' : IDL.Text,
    'docType' : DocType,
  });
  const Checkpoint = IDL.Variant({
    'checkin' : IDL.Null,
    'security' : IDL.Null,
    'boarding' : IDL.Null,
  });
  const CongestionLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const QueueStatusState = IDL.Record({
    'checkpoint' : Checkpoint,
    'lastUpdated' : IDL.Int,
    'waitMinutes' : IDL.Nat,
    'congestionLevel' : CongestionLevel,
  });
  const DisruptionType = IDL.Variant({
    'overbooking' : IDL.Null,
    'delay' : IDL.Null,
    'cancellation' : IDL.Null,
    'missedConnection' : IDL.Null,
  });
  const TravelRightsInfoState = IDL.Record({
    'actionSteps' : IDL.Vec(IDL.Text),
    'compensationAmount' : IDL.Nat,
    'disruptionType' : DisruptionType,
    'applicableRegulation' : IDL.Text,
    'keyRights' : IDL.Vec(IDL.Text),
  });
  const TripState = IDL.Record({
    'bookingReference' : IDL.Text,
    'arrivalAirport' : IDL.Text,
    'flightNumber' : IDL.Text,
    'seat' : IDL.Text,
    'departureTimestamp' : IDL.Int,
    'passengerName' : IDL.Text,
    'airline' : IDL.Text,
    'departureAirport' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Status = IDL.Variant({
    'delayed' : IDL.Null,
    'cancelled' : IDL.Null,
    'gateChange' : IDL.Null,
    'onTime' : IDL.Null,
  });
  const FlightStatusState = IDL.Record({
    'status' : Status,
    'flightNumber' : IDL.Text,
    'gate' : IDL.Text,
    'message' : IDL.Text,
    'delayMinutes' : IDL.Opt(IDL.Nat),
    'terminal' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAiMessage' : IDL.Func([AiMessageState], [], []),
    'addOrUpdateBaggageItem' : IDL.Func([BaggageItemState], [], []),
    'addOrUpdateDigitalIdentityDoc' : IDL.Func(
        [DigitalIdentityDocState],
        [],
        [],
      ),
    'addOrUpdateQueueStatus' : IDL.Func([QueueStatusState], [], []),
    'addTravelRightsInfo' : IDL.Func([TravelRightsInfoState], [], []),
    'addTrip' : IDL.Func([TripState], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'computeLeaveHomeTime' : IDL.Func([], [IDL.Int], ['query']),
    'getAiMessages' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AiMessageState)],
        ['query'],
      ),
    'getBaggageItems' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(BaggageItemState)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDigitalIdentityDocs' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DigitalIdentityDocState)],
        ['query'],
      ),
    'getFlightStatus' : IDL.Func([IDL.Text], [FlightStatusState], ['query']),
    'getQueueStatuses' : IDL.Func([], [IDL.Vec(QueueStatusState)], ['query']),
    'getTravelRightsInfo' : IDL.Func(
        [IDL.Text],
        [TravelRightsInfoState],
        ['query'],
      ),
    'getTrip' : IDL.Func([IDL.Principal], [TripState], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedDemoData' : IDL.Func([], [], []),
    'updateFlightStatus' : IDL.Func([FlightStatusState], [], []),
  });
};

export const init = ({ IDL }) => { return []; };