/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AiMessageState {
  'content' : string,
  'role' : Role,
  'timestamp' : bigint,
}
export interface BaggageItemState {
  'status' : Status__1,
  'lastUpdated' : bigint,
  'description' : string,
  'tagNumber' : string,
}
export type Checkpoint = { 'checkin' : null } |
  { 'security' : null } |
  { 'boarding' : null };
export type CongestionLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface DigitalIdentityDocState {
  'expiryDate' : bigint,
  'isReady' : boolean,
  'notes' : string,
  'docType' : DocType,
}
export type DisruptionType = { 'overbooking' : null } |
  { 'delay' : null } |
  { 'cancellation' : null } |
  { 'missedConnection' : null };
export type DocType = { 'passport' : null } |
  { 'visa' : null } |
  { 'hotelBooking' : null } |
  { 'boardingPass' : null } |
  { 'travelInsurance' : null };
export interface FlightStatusState {
  'status' : Status,
  'flightNumber' : string,
  'gate' : string,
  'message' : string,
  'delayMinutes' : [] | [bigint],
  'terminal' : string,
}
export interface QueueStatusState {
  'checkpoint' : Checkpoint,
  'lastUpdated' : bigint,
  'waitMinutes' : bigint,
  'congestionLevel' : CongestionLevel,
}
export type Role = { 'user' : null } |
  { 'assistant' : null };
export type Status = { 'delayed' : null } |
  { 'cancelled' : null } |
  { 'gateChange' : null } |
  { 'onTime' : null };
export type Status__1 = { 'arrived' : null } |
  { 'loaded' : null } |
  { 'inTransit' : null } |
  { 'collected' : null } |
  { 'checkedIn' : null } |
  { 'atCarousel' : null };
export interface TravelRightsInfoState {
  'actionSteps' : Array<string>,
  'compensationAmount' : bigint,
  'disruptionType' : DisruptionType,
  'applicableRegulation' : string,
  'keyRights' : Array<string>,
}
export interface TripState {
  'bookingReference' : string,
  'arrivalAirport' : string,
  'flightNumber' : string,
  'seat' : string,
  'departureTimestamp' : bigint,
  'passengerName' : string,
  'airline' : string,
  'departureAirport' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAiMessage' : ActorMethod<[AiMessageState], undefined>,
  'addOrUpdateBaggageItem' : ActorMethod<[BaggageItemState], undefined>,
  'addOrUpdateDigitalIdentityDoc' : ActorMethod<
    [DigitalIdentityDocState],
    undefined
  >,
  'addOrUpdateQueueStatus' : ActorMethod<[QueueStatusState], undefined>,
  'addTravelRightsInfo' : ActorMethod<[TravelRightsInfoState], undefined>,
  'addTrip' : ActorMethod<[TripState], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'computeLeaveHomeTime' : ActorMethod<[], bigint>,
  'getAiMessages' : ActorMethod<[Principal], Array<AiMessageState>>,
  'getBaggageItems' : ActorMethod<[Principal], Array<BaggageItemState>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDigitalIdentityDocs' : ActorMethod<
    [Principal],
    Array<DigitalIdentityDocState>
  >,
  'getFlightStatus' : ActorMethod<[string], FlightStatusState>,
  'getQueueStatuses' : ActorMethod<[], Array<QueueStatusState>>,
  'getTravelRightsInfo' : ActorMethod<[string], TravelRightsInfoState>,
  'getTrip' : ActorMethod<[Principal], TripState>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedDemoData' : ActorMethod<[], undefined>,
  'updateFlightStatus' : ActorMethod<[FlightStatusState], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];