/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AiMessageState {
    content: string;
    role: Role;
    timestamp: bigint;
}
export interface QueueStatusState {
    checkpoint: Checkpoint;
    lastUpdated: bigint;
    waitMinutes: bigint;
    congestionLevel: CongestionLevel;
}
export interface BaggageItemState {
    status: Status__1;
    lastUpdated: bigint;
    description: string;
    tagNumber: string;
}
export interface DigitalIdentityDocState {
    expiryDate: bigint;
    isReady: boolean;
    notes: string;
    docType: DocType;
}
export interface FlightStatusState {
    status: Status;
    flightNumber: string;
    gate: string;
    message: string;
    delayMinutes?: bigint;
    terminal: string;
}
export interface TripState {
    bookingReference: string;
    arrivalAirport: string;
    flightNumber: string;
    seat: string;
    departureTimestamp: bigint;
    passengerName: string;
    airline: string;
    departureAirport: string;
}
export interface TravelRightsInfoState {
    actionSteps: Array<string>;
    compensationAmount: bigint;
    disruptionType: DisruptionType;
    applicableRegulation: string;
    keyRights: Array<string>;
}
export interface UserProfile {
    name: string;
}
export enum Checkpoint {
    checkin = "checkin",
    security = "security",
    boarding = "boarding"
}
export enum CongestionLevel {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum DisruptionType {
    overbooking = "overbooking",
    delay = "delay",
    cancellation = "cancellation",
    missedConnection = "missedConnection"
}
export enum DocType {
    passport = "passport",
    visa = "visa",
    hotelBooking = "hotelBooking",
    boardingPass = "boardingPass",
    travelInsurance = "travelInsurance"
}
export enum Role {
    user = "user",
    assistant = "assistant"
}
export enum Status {
    delayed = "delayed",
    cancelled = "cancelled",
    gateChange = "gateChange",
    onTime = "onTime"
}
export enum Status__1 {
    arrived = "arrived",
    loaded = "loaded",
    inTransit = "inTransit",
    collected = "collected",
    checkedIn = "checkedIn",
    atCarousel = "atCarousel"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAiMessage(message: AiMessageState): Promise<void>;
    addOrUpdateBaggageItem(baggageItem: BaggageItemState): Promise<void>;
    addOrUpdateDigitalIdentityDoc(doc: DigitalIdentityDocState): Promise<void>;
    addOrUpdateQueueStatus(queueStatus: QueueStatusState): Promise<void>;
    addTravelRightsInfo(info: TravelRightsInfoState): Promise<void>;
    addTrip(trip: TripState): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    computeLeaveHomeTime(): Promise<bigint>;
    getAiMessages(user: Principal): Promise<Array<AiMessageState>>;
    getBaggageItems(user: Principal): Promise<Array<BaggageItemState>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDigitalIdentityDocs(user: Principal): Promise<Array<DigitalIdentityDocState>>;
    getFlightStatus(flightNumber: string): Promise<FlightStatusState>;
    getQueueStatuses(): Promise<Array<QueueStatusState>>;
    getTravelRightsInfo(disruptionType: string): Promise<TravelRightsInfoState>;
    getTrip(user: Principal): Promise<TripState>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedDemoData(): Promise<void>;
    updateFlightStatus(flightStatus: FlightStatusState): Promise<void>;
}
import type { AiMessageState as _AiMessageState, BaggageItemState as _BaggageItemState, Checkpoint as _Checkpoint, CongestionLevel as _CongestionLevel, DigitalIdentityDocState as _DigitalIdentityDocState, DisruptionType as _DisruptionType, DocType as _DocType, FlightStatusState as _FlightStatusState, QueueStatusState as _QueueStatusState, Role as _Role, Status as _Status, Status__1 as _Status__1, TravelRightsInfoState as _TravelRightsInfoState, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAiMessage(arg0: AiMessageState): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAiMessage(to_candid_AiMessageState_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAiMessage(to_candid_AiMessageState_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addOrUpdateBaggageItem(arg0: BaggageItemState): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateBaggageItem(to_candid_BaggageItemState_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateBaggageItem(to_candid_BaggageItemState_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addOrUpdateDigitalIdentityDoc(arg0: DigitalIdentityDocState): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateDigitalIdentityDoc(to_candid_DigitalIdentityDocState_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateDigitalIdentityDoc(to_candid_DigitalIdentityDocState_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addOrUpdateQueueStatus(arg0: QueueStatusState): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateQueueStatus(to_candid_QueueStatusState_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateQueueStatus(to_candid_QueueStatusState_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTravelRightsInfo(arg0: TravelRightsInfoState): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTravelRightsInfo(to_candid_TravelRightsInfoState_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTravelRightsInfo(to_candid_TravelRightsInfoState_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTrip(arg0: TripState): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrip(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n23(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n23(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async computeLeaveHomeTime(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.computeLeaveHomeTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.computeLeaveHomeTime();
            return result;
        }
    }
    async getAiMessages(arg0: Principal): Promise<Array<AiMessageState>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAiMessages(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAiMessages(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBaggageItems(arg0: Principal): Promise<Array<BaggageItemState>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBaggageItems(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBaggageItems(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDigitalIdentityDocs(arg0: Principal): Promise<Array<DigitalIdentityDocState>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDigitalIdentityDocs(arg0);
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDigitalIdentityDocs(arg0);
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFlightStatus(arg0: string): Promise<FlightStatusState> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlightStatus(arg0);
                return from_candid_FlightStatusState_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlightStatus(arg0);
            return from_candid_FlightStatusState_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQueueStatuses(): Promise<Array<QueueStatusState>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQueueStatuses();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQueueStatuses();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTravelRightsInfo(arg0: string): Promise<TravelRightsInfoState> {
        if (this.processError) {
            try {
                const result = await this.actor.getTravelRightsInfo(arg0);
                return from_candid_TravelRightsInfoState_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTravelRightsInfo(arg0);
            return from_candid_TravelRightsInfoState_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrip(arg0: Principal): Promise<TripState> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrip(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async seedDemoData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDemoData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDemoData();
            return result;
        }
    }
    async updateFlightStatus(arg0: FlightStatusState): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFlightStatus(to_candid_FlightStatusState_n59(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFlightStatus(to_candid_FlightStatusState_n59(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AiMessageState_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AiMessageState): AiMessageState {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_BaggageItemState_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BaggageItemState): BaggageItemState {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Checkpoint_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Checkpoint): Checkpoint {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_CongestionLevel_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CongestionLevel): CongestionLevel {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_DigitalIdentityDocState_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DigitalIdentityDocState): DigitalIdentityDocState {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_DisruptionType_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DisruptionType): DisruptionType {
    return from_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function from_candid_DocType_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocType): DocType {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_FlightStatusState_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FlightStatusState): FlightStatusState {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_QueueStatusState_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QueueStatusState): QueueStatusState {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Status__1_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status__1): Status__1 {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_TravelRightsInfoState_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TravelRightsInfoState): TravelRightsInfoState {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    role: _Role;
    timestamp: bigint;
}): {
    content: string;
    role: Role;
    timestamp: bigint;
} {
    return {
        content: value.content,
        role: from_candid_Role_n28(_uploadFile, _downloadFile, value.role),
        timestamp: value.timestamp
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _Status__1;
    lastUpdated: bigint;
    description: string;
    tagNumber: string;
}): {
    status: Status__1;
    lastUpdated: bigint;
    description: string;
    tagNumber: string;
} {
    return {
        status: from_candid_Status__1_n33(_uploadFile, _downloadFile, value.status),
        lastUpdated: value.lastUpdated,
        description: value.description,
        tagNumber: value.tagNumber
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expiryDate: bigint;
    isReady: boolean;
    notes: string;
    docType: _DocType;
}): {
    expiryDate: bigint;
    isReady: boolean;
    notes: string;
    docType: DocType;
} {
    return {
        expiryDate: value.expiryDate,
        isReady: value.isReady,
        notes: value.notes,
        docType: from_candid_DocType_n41(_uploadFile, _downloadFile, value.docType)
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _Status;
    flightNumber: string;
    gate: string;
    message: string;
    delayMinutes: [] | [bigint];
    terminal: string;
}): {
    status: Status;
    flightNumber: string;
    gate: string;
    message: string;
    delayMinutes?: bigint;
    terminal: string;
} {
    return {
        status: from_candid_Status_n45(_uploadFile, _downloadFile, value.status),
        flightNumber: value.flightNumber,
        gate: value.gate,
        message: value.message,
        delayMinutes: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.delayMinutes)),
        terminal: value.terminal
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    checkpoint: _Checkpoint;
    lastUpdated: bigint;
    waitMinutes: bigint;
    congestionLevel: _CongestionLevel;
}): {
    checkpoint: Checkpoint;
    lastUpdated: bigint;
    waitMinutes: bigint;
    congestionLevel: CongestionLevel;
} {
    return {
        checkpoint: from_candid_Checkpoint_n51(_uploadFile, _downloadFile, value.checkpoint),
        lastUpdated: value.lastUpdated,
        waitMinutes: value.waitMinutes,
        congestionLevel: from_candid_CongestionLevel_n53(_uploadFile, _downloadFile, value.congestionLevel)
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    actionSteps: Array<string>;
    compensationAmount: bigint;
    disruptionType: _DisruptionType;
    applicableRegulation: string;
    keyRights: Array<string>;
}): {
    actionSteps: Array<string>;
    compensationAmount: bigint;
    disruptionType: DisruptionType;
    applicableRegulation: string;
    keyRights: Array<string>;
} {
    return {
        actionSteps: value.actionSteps,
        compensationAmount: value.compensationAmount,
        disruptionType: from_candid_DisruptionType_n57(_uploadFile, _downloadFile, value.disruptionType),
        applicableRegulation: value.applicableRegulation,
        keyRights: value.keyRights
    };
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    assistant: null;
}): Role {
    return "user" in value ? Role.user : "assistant" in value ? Role.assistant : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    arrived: null;
} | {
    loaded: null;
} | {
    inTransit: null;
} | {
    collected: null;
} | {
    checkedIn: null;
} | {
    atCarousel: null;
}): Status__1 {
    return "arrived" in value ? Status__1.arrived : "loaded" in value ? Status__1.loaded : "inTransit" in value ? Status__1.inTransit : "collected" in value ? Status__1.collected : "checkedIn" in value ? Status__1.checkedIn : "atCarousel" in value ? Status__1.atCarousel : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    passport: null;
} | {
    visa: null;
} | {
    hotelBooking: null;
} | {
    boardingPass: null;
} | {
    travelInsurance: null;
}): DocType {
    return "passport" in value ? DocType.passport : "visa" in value ? DocType.visa : "hotelBooking" in value ? DocType.hotelBooking : "boardingPass" in value ? DocType.boardingPass : "travelInsurance" in value ? DocType.travelInsurance : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    delayed: null;
} | {
    cancelled: null;
} | {
    gateChange: null;
} | {
    onTime: null;
}): Status {
    return "delayed" in value ? Status.delayed : "cancelled" in value ? Status.cancelled : "gateChange" in value ? Status.gateChange : "onTime" in value ? Status.onTime : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    checkin: null;
} | {
    security: null;
} | {
    boarding: null;
}): Checkpoint {
    return "checkin" in value ? Checkpoint.checkin : "security" in value ? Checkpoint.security : "boarding" in value ? Checkpoint.boarding : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): CongestionLevel {
    return "low" in value ? CongestionLevel.low : "high" in value ? CongestionLevel.high : "medium" in value ? CongestionLevel.medium : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    overbooking: null;
} | {
    delay: null;
} | {
    cancellation: null;
} | {
    missedConnection: null;
}): DisruptionType {
    return "overbooking" in value ? DisruptionType.overbooking : "delay" in value ? DisruptionType.delay : "cancellation" in value ? DisruptionType.cancellation : "missedConnection" in value ? DisruptionType.missedConnection : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AiMessageState>): Array<AiMessageState> {
    return value.map((x)=>from_candid_AiMessageState_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BaggageItemState>): Array<BaggageItemState> {
    return value.map((x)=>from_candid_BaggageItemState_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DigitalIdentityDocState>): Array<DigitalIdentityDocState> {
    return value.map((x)=>from_candid_DigitalIdentityDocState_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QueueStatusState>): Array<QueueStatusState> {
    return value.map((x)=>from_candid_QueueStatusState_n49(_uploadFile, _downloadFile, x));
}
function to_candid_AiMessageState_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AiMessageState): _AiMessageState {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_BaggageItemState_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BaggageItemState): _BaggageItemState {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Checkpoint_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Checkpoint): _Checkpoint {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_CongestionLevel_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CongestionLevel): _CongestionLevel {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_DigitalIdentityDocState_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DigitalIdentityDocState): _DigitalIdentityDocState {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_DisruptionType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DisruptionType): _DisruptionType {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_DocType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocType): _DocType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_FlightStatusState_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FlightStatusState): _FlightStatusState {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_QueueStatusState_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QueueStatusState): _QueueStatusState {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Status__1_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): _Status__1 {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function to_candid_TravelRightsInfoState_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TravelRightsInfoState): _TravelRightsInfoState {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expiryDate: bigint;
    isReady: boolean;
    notes: string;
    docType: DocType;
}): {
    expiryDate: bigint;
    isReady: boolean;
    notes: string;
    docType: _DocType;
} {
    return {
        expiryDate: value.expiryDate,
        isReady: value.isReady,
        notes: value.notes,
        docType: to_candid_DocType_n11(_uploadFile, _downloadFile, value.docType)
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    checkpoint: Checkpoint;
    lastUpdated: bigint;
    waitMinutes: bigint;
    congestionLevel: CongestionLevel;
}): {
    checkpoint: _Checkpoint;
    lastUpdated: bigint;
    waitMinutes: bigint;
    congestionLevel: _CongestionLevel;
} {
    return {
        checkpoint: to_candid_Checkpoint_n15(_uploadFile, _downloadFile, value.checkpoint),
        lastUpdated: value.lastUpdated,
        waitMinutes: value.waitMinutes,
        congestionLevel: to_candid_CongestionLevel_n17(_uploadFile, _downloadFile, value.congestionLevel)
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    role: Role;
    timestamp: bigint;
}): {
    content: string;
    role: _Role;
    timestamp: bigint;
} {
    return {
        content: value.content,
        role: to_candid_Role_n3(_uploadFile, _downloadFile, value.role),
        timestamp: value.timestamp
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    actionSteps: Array<string>;
    compensationAmount: bigint;
    disruptionType: DisruptionType;
    applicableRegulation: string;
    keyRights: Array<string>;
}): {
    actionSteps: Array<string>;
    compensationAmount: bigint;
    disruptionType: _DisruptionType;
    applicableRegulation: string;
    keyRights: Array<string>;
} {
    return {
        actionSteps: value.actionSteps,
        compensationAmount: value.compensationAmount,
        disruptionType: to_candid_DisruptionType_n21(_uploadFile, _downloadFile, value.disruptionType),
        applicableRegulation: value.applicableRegulation,
        keyRights: value.keyRights
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: Status__1;
    lastUpdated: bigint;
    description: string;
    tagNumber: string;
}): {
    status: _Status__1;
    lastUpdated: bigint;
    description: string;
    tagNumber: string;
} {
    return {
        status: to_candid_Status__1_n7(_uploadFile, _downloadFile, value.status),
        lastUpdated: value.lastUpdated,
        description: value.description,
        tagNumber: value.tagNumber
    };
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: Status;
    flightNumber: string;
    gate: string;
    message: string;
    delayMinutes?: bigint;
    terminal: string;
}): {
    status: _Status;
    flightNumber: string;
    gate: string;
    message: string;
    delayMinutes: [] | [bigint];
    terminal: string;
} {
    return {
        status: to_candid_Status_n61(_uploadFile, _downloadFile, value.status),
        flightNumber: value.flightNumber,
        gate: value.gate,
        message: value.message,
        delayMinutes: value.delayMinutes ? candid_some(value.delayMinutes) : candid_none(),
        terminal: value.terminal
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocType): {
    passport: null;
} | {
    visa: null;
} | {
    hotelBooking: null;
} | {
    boardingPass: null;
} | {
    travelInsurance: null;
} {
    return value == DocType.passport ? {
        passport: null
    } : value == DocType.visa ? {
        visa: null
    } : value == DocType.hotelBooking ? {
        hotelBooking: null
    } : value == DocType.boardingPass ? {
        boardingPass: null
    } : value == DocType.travelInsurance ? {
        travelInsurance: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Checkpoint): {
    checkin: null;
} | {
    security: null;
} | {
    boarding: null;
} {
    return value == Checkpoint.checkin ? {
        checkin: null
    } : value == Checkpoint.security ? {
        security: null
    } : value == Checkpoint.boarding ? {
        boarding: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CongestionLevel): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == CongestionLevel.low ? {
        low: null
    } : value == CongestionLevel.high ? {
        high: null
    } : value == CongestionLevel.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DisruptionType): {
    overbooking: null;
} | {
    delay: null;
} | {
    cancellation: null;
} | {
    missedConnection: null;
} {
    return value == DisruptionType.overbooking ? {
        overbooking: null
    } : value == DisruptionType.delay ? {
        delay: null
    } : value == DisruptionType.cancellation ? {
        cancellation: null
    } : value == DisruptionType.missedConnection ? {
        missedConnection: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    user: null;
} | {
    assistant: null;
} {
    return value == Role.user ? {
        user: null
    } : value == Role.assistant ? {
        assistant: null
    } : value;
}
function to_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    delayed: null;
} | {
    cancelled: null;
} | {
    gateChange: null;
} | {
    onTime: null;
} {
    return value == Status.delayed ? {
        delayed: null
    } : value == Status.cancelled ? {
        cancelled: null
    } : value == Status.gateChange ? {
        gateChange: null
    } : value == Status.onTime ? {
        onTime: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): {
    arrived: null;
} | {
    loaded: null;
} | {
    inTransit: null;
} | {
    collected: null;
} | {
    checkedIn: null;
} | {
    atCarousel: null;
} {
    return value == Status__1.arrived ? {
        arrived: null
    } : value == Status__1.loaded ? {
        loaded: null
    } : value == Status__1.inTransit ? {
        inTransit: null
    } : value == Status__1.collected ? {
        collected: null
    } : value == Status__1.checkedIn ? {
        checkedIn: null
    } : value == Status__1.atCarousel ? {
        atCarousel: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
